name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: provide steps to reproduce the problem
  - type: textarea
    attributes:
      label: Exception or Error
      description: provide error logs
  - type: input
    attributes:
      label: Dump
      description: Run `/pp dump` in-game and share the link
      placeholder: https://mclo.gs/
    validations:
      required: true
