name: PluginPortal
main: gg.flyte.pluginportal.plugin.PluginPortal
author: Flyte
version: ${version}
description: A package manager for plugins.
api-version: 1.13
folia-supported: true
website: https://flyte.gg
commands:
  pp:
    description: Manage plugins on this server
    aliases: [pluginportal, ppm]
permissions:
  pluginportal.*:
    default: op
    children:
      pluginportal.admin: true
      pluginportal.manage.*: true
