/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.10.0")
    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    javaTarget(17)
    withSourcesJar()
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks {
    processResources {
        println("Processing resources")
        // print out the files that are being processed
        sourceSets.main.get().resources.srcDirs.forEach {
            println("Processing resources from $it")
            println("Child files: ${it.listFiles()?.map { it.name }}")
        }

        filesMatching(listOf("plugin.yml")) {
            println("Processing plugin.yml")
            println("Project version before expansion: ${project.version}")
            println("Replacing version in ${project.version}")
            expand("version" to project.version)
            println("Project version after expansion: ${project.version}")
        }
    }

    test {
        useJUnitPlatform()
    }
}