import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.johnrengelman.shadow")
}

tasks {
    val shadowJar = named<ShadowJar>("shadowJar") {
        archiveClassifier.set("")
        archiveFileName.set("PluginPortal-${project.version}.jar")


        minimize()
        relocate("com.google.gson", "gg.flyte.pluginportal.libs.gson")
        relocate("org.bstats", "gg.flyte.pluginportal.libs.bstats")
    }
    named("build") {
        dependsOn(shadowJar)
    }
}