/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("pp.kotlin-library-conventions")
}

dependencies {
    implementation("com.google.code.gson:gson:2.11.0")
    api("com.squareup.okhttp3:okhttp:4.12.0")
}
