name: Build and Test
on:
  push:
    branches:
      - master
      - master-premium

jobs:
  publish:
    if: github.repository_owner == 'flytegg'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Test
        run: ./gradlew test